const testDetails = [
  {
    id: 1,
    testTabId: "new",
    testName: "Experiment 1",
    testType: "Technical",
    subTopic: "Round 1",
    duration: 50,
    totalMarks: 20,
    negativeMarks: 0,
    score: 0,
    result: "",
    status: "Start",
    updatedAt: "07-05-2025",
  },
  {
    id: 2,
    testTabId: "new",
    testName: "Experiment 2",
    testType: "Technical",
    subTopic: "Round 1",
    duration: 50,
    totalMarks: 20,
    negativeMarks: 0,
    score: 0,
    result: "",
    status: "Start",
    updatedAt: "07-05-2025",
  },
  {
    id: 3,
    testTabId: "attempted",
    testName: "Experiment 3",
    testType: "Technical",
    subTopic: "Round 1",
    duration: 50,
    totalMarks: 20,
    negativeMarks: 0,
    score: 18,
    result: "Pass",
    status: "Completed",
    updatedAt: "07-05-2025",
  },
  {
    id: 4,
    testTabId: "attempted",
    testName: "Experiment 4",
    testType: "Technical",
    subTopic: "Round 1",
    duration: 50,
    totalMarks: 20,
    negativeMarks: 0,
    score: 5,
    result: "Failed",
    status: "Reattempt",
    updatedAt: "07-05-2025",
  },
  {
    id: 5,
    testTabId: "missed",
    testName: "Experiment 5",
    testType: "Technical",
    subTopic: "Round 1",
    duration: 50,
    totalMarks: 20,
    negativeMarks: 0,
    score: "",
    result: "",
    status: "Completed",
    updatedAt: "07-05-2025",
  },
];

export default testDetails;
